### ISSUE TITLE
Should we always get the latest gaston?

### ISSUE THREAD

**Issue by shawninder** [vigour-io/packer-server#17]
I wonder if this is perhaps too restrictive. Wouldn't it be better to let the app decide which version of gaston it needs, and only if none is provided, fallback on the latest version?

**Comment by shawninder** [comment]
It also seems that gaston is being installed everytime the packer-server launches, making the launch process super long

**Comment by shawninder** [comment]
latest mail-man#develop now checks whether latest gaston is there before getting it, greatly speeding up launch time. A further improvement would be to let the app decide of the target version

**Comment by ninjatux** [comment]
@shawninder is this still a thing?

**Comment by shawninder** [comment]
No, now we just expect gaston to be installed globally, but even that is only for testing. Also, I plan to stop relying on gaston for tests so `packer-server`, `mail-man` and `git-spy` will be completely unrelated to `gaston`.
