### ISSUE TITLE
[UA] map user agent to specific build

### ISSUE THREAD

**Issue by andrepadez** [vigour-io/packer-server#2]
right now, through the user-agent string, we're getting info like:
```
{ browser: 'safari',
  version: 531.2,
  prefix: 'webkit',
  platform: 'samsung',
  device: 'tv' }
or
{ browser: 'chrome',
  version: 46,
  prefix: 'webkit',
  platform: 'mac',
  device: 'desktop' } 
```

we need a reliable and generalised way to map this information to the different build "keys" that will be generated by the VigourNative build process:
samsungtv, web, lgtv, ios, android...

@jimdebeer @renancarvalho @shawninder @youzi

**Comment by shawninder** [comment]
We could have the native builds request the app with a special query parameter indicating which "platform" they are running (the key you mention). Something like `http://5thdimension.vigour.io?platform=ios`. Perhaps using `ua.platform` is good enough, but this seems pretty bulletproof.

Thoughts?

**Comment by shawninder** [comment]
I asked @avdwerff and @michielibiza to have the webviews provide extra info in the user-agent string to help us with this
