### ISSUE TITLE
Update MTV Packer for new JSON-LD structure

### ISSUE THREAD

**Issue by ricksmit3000** [vigour-io/packer-server#43]
For serving meta data we use a set of JSON-LD's that corresponds with the requested page, in the current setup we only serve english title and descriptions, and we would like to display other languages as well.

The JSON-LD's will have the following structure [language-code][franchise-id].[season-number][episode-number] e.g. nl.977.2.1

When the packer gets a request where the url is appended with a language code, it needs to serve the corresponding JSON-LD.

**Comment by shawninder** [comment]
This issue was moved to vigour-io/ferry#38
